source 'https://cdn.cocoapods.org'


workspace '../CocoaPodsTest'
platform :ios, '16.0'
inhibit_all_warnings!


target 'Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#  pod 'CocoaPodsTestLibrary', :git => 'https://github.com/gongwen/CocoaPodsTest'
#  pod 'CocoaPodsTestLibrary/ModuleCore', :git => 'https://github.com/gongwen/CocoaPodsTest'
#  pod 'CocoaPodsTestLibrary', :path => '../'
pod 'CocoaPodsTestLibrary/ModuleCore', :path => '../'
pod 'CocoaPodsTestLibrary/ModuleA', :path => '../'

end

#pod deintegrate && pod install
