source 'https://cdn.cocoapods.org'


workspace '../CocoaPodsTest'
platform :ios, '16.0'
inhibit_all_warnings!


target 'Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#  打包模式
#  pod 'CocoaPodsTestLibrary', :git => 'git@github.com:gongwen/CocoaPodsTest.git', :tag => '1.0.0-alpha.4'
#pod 'CocoaPodsTestLibrary/ModuleCore', :git => 'git@github.com:gongwen/CocoaPodsTest.git', :tag => '1.0.0-alpha.4'
#pod 'CocoaPodsTestLibrary/ModuleA', :git => 'git@github.com:gongwen/CocoaPodsTest.git', :tag => '1.0.0-alpha.4'

# 调试模式
#  pod 'CocoaPodsTestLibrary', :path => '../'
pod 'CocoaPodsTestLibrary/ModuleCore', :path => '../'
pod 'CocoaPodsTestLibrary/ModuleA', :path => '../'

end
