#source 'https://cdn.cocoapods.org'
source 'http://git.amberweather.com/game_libs/cocoapodsspecs.git'


workspace '../CocoaPodsTest'
platform :ios, '16.0'
inhibit_all_warnings!


target 'Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CocoaPodsTestLibrary',:git => 'https://github.com/gongwen/CocoaPodsTest'

end
